// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package movie_resevation

import (
	"database/sql"

	"github.com/google/uuid"
)

type MvGenre struct {
	ID    uuid.UUID
	Title sql.NullString
}

type MvMovie struct {
	ID          uuid.UUID
	Title       sql.NullString
	Description sql.NullString
	// filename
	PosterImage sql.NullString
	// extension
	PosterExt     sql.NullString
	Minutes       sql.NullInt32
	ReleaseDate   sql.NullTime
	Language      sql.NullString
	CountryOrigin sql.NullString
}

type MvMovieGenre struct {
	MovieID uuid.NullUUID
	GenreID uuid.NullUUID
}

type StRoom struct {
	ID    uuid.UUID
	Title sql.NullString
}

type StRoomSeat struct {
	RoomID uuid.NullUUID
	SeatID uuid.NullUUID
}

type StSeat struct {
	ID   uuid.UUID
	Code sql.NullString
}

type StShowtime struct {
	ID             uuid.UUID
	MovieID        uuid.NullUUID
	Price          sql.NullString
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	AvailableSeats sql.NullInt32
}

type StShowtimeRoom struct {
	ShowtimeID uuid.NullUUID
	RoomID     uuid.NullUUID
}

type StTicket struct {
	ID         uuid.UUID
	ShowtimeID uuid.NullUUID
	RoomID     uuid.NullUUID
	SeatID     uuid.NullUUID
	UserID     uuid.NullUUID
	FirstName  sql.NullString
	LastName   sql.NullString
	Paid       sql.NullString
}

type SyRole struct {
	ID    uuid.UUID
	Title sql.NullString
}

type SyUser struct {
	ID         uuid.UUID
	Email      sql.NullString
	Password   sql.NullString
	SaltRounds sql.NullInt32
	FirstName  sql.NullString
	LastName   sql.NullString
	Birthdate  sql.NullTime
}

type SyUserRole struct {
	UserID uuid.NullUUID
	RoleID uuid.NullUUID
}
