// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package movie_resevation

import (
	"database/sql"

	"github.com/google/uuid"
)

type MvGenre struct {
	ID    uuid.UUID      `json:"id"`
	Title sql.NullString `json:"title"`
}

type MvMovie struct {
	ID          uuid.UUID      `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	// filename
	PosterImage sql.NullString `json:"poster_image"`
	// extension
	PosterExt     sql.NullString `json:"poster_ext"`
	Minutes       sql.NullInt32  `json:"minutes"`
	ReleaseDate   sql.NullTime   `json:"release_date"`
	Language      sql.NullString `json:"language"`
	CountryOrigin sql.NullString `json:"country_origin"`
}

type MvMovieGenre struct {
	MovieID uuid.NullUUID `json:"movie_id"`
	GenreID uuid.NullUUID `json:"genre_id"`
}

type StRoom struct {
	ID    uuid.UUID      `json:"id"`
	Title sql.NullString `json:"title"`
}

type StRoomSeat struct {
	RoomID uuid.NullUUID `json:"room_id"`
	SeatID uuid.NullUUID `json:"seat_id"`
}

type StSeat struct {
	ID   uuid.UUID      `json:"id"`
	Code sql.NullString `json:"code"`
}

type StShowtime struct {
	ID             uuid.UUID      `json:"id"`
	MovieID        uuid.NullUUID  `json:"movie_id"`
	Price          sql.NullString `json:"price"`
	StartTime      sql.NullTime   `json:"start_time"`
	EndTime        sql.NullTime   `json:"end_time"`
	AvailableSeats sql.NullInt32  `json:"available_seats"`
}

type StShowtimeRoom struct {
	ShowtimeID uuid.NullUUID `json:"showtime_id"`
	RoomID     uuid.NullUUID `json:"room_id"`
}

type StTicket struct {
	ID         uuid.UUID      `json:"id"`
	ShowtimeID uuid.NullUUID  `json:"showtime_id"`
	RoomID     uuid.NullUUID  `json:"room_id"`
	SeatID     uuid.NullUUID  `json:"seat_id"`
	UserID     uuid.NullUUID  `json:"user_id"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Paid       sql.NullString `json:"paid"`
}

type SyRole struct {
	ID    uuid.UUID      `json:"id"`
	Title sql.NullString `json:"title"`
}

type SyUser struct {
	ID         uuid.UUID      `json:"id"`
	Email      sql.NullString `json:"email"`
	Password   sql.NullString `json:"password"`
	SaltRounds sql.NullInt32  `json:"salt_rounds"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Birthdate  sql.NullTime   `json:"birthdate"`
}

type SyUserRole struct {
	UserID uuid.NullUUID `json:"user_id"`
	RoleID uuid.NullUUID `json:"role_id"`
}
