// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package movie_resevation

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type GenderEnum string

const (
	GenderEnumM GenderEnum = "M"
	GenderEnumF GenderEnum = "F"
)

func (e *GenderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderEnum(s)
	case string:
		*e = GenderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderEnum: %T", src)
	}
	return nil
}

type NullGenderEnum struct {
	GenderEnum GenderEnum
	Valid      bool // Valid is true if GenderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GenderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderEnum), nil
}

type MvGenre struct {
	ID    uuid.UUID
	Title sql.NullString
}

type MvMovie struct {
	ID          uuid.UUID
	Title       sql.NullString
	Description sql.NullString
	// filename
	PosterImage sql.NullString
	// extension
	PosterExt     sql.NullString
	Minutes       sql.NullInt32
	ReleaseDate   sql.NullTime
	Language      sql.NullString
	CountryOrigin sql.NullString
}

type MvMovieGenre struct {
	MovieID uuid.NullUUID
	GenreID uuid.NullUUID
}

type MvMovieStaff struct {
	PersonID uuid.NullUUID
	MovieID  uuid.NullUUID
	RoleID   uuid.NullUUID
	// Nullable for crew roles
	CharacterName sql.NullString
}

type MvPerson struct {
	ID        uuid.UUID
	FirstName sql.NullString
	LastName  sql.NullString
	Gender    NullGenderEnum
}

type MvRole struct {
	ID    uuid.UUID
	Title sql.NullString
}

type StRoom struct {
	ID    uuid.UUID
	Title sql.NullString
}

type StRoomSeat struct {
	RoomID uuid.NullUUID
	SeatID uuid.NullUUID
}

type StSeat struct {
	ID   uuid.UUID
	Code sql.NullString
}

type StShowtime struct {
	ID             uuid.UUID
	MovieID        uuid.NullUUID
	Price          sql.NullString
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	AvailableSeats sql.NullInt32
}

type StShowtimeRoom struct {
	ShowtimeID uuid.NullUUID
	RoomID     uuid.NullUUID
}

type StTicket struct {
	ID         uuid.UUID
	ShowtimeID uuid.NullUUID
	RoomID     uuid.NullUUID
	SeatID     uuid.NullUUID
	UserID     uuid.NullUUID
	FirstName  sql.NullString
	LastName   sql.NullString
	Paid       sql.NullString
}

type SyRole struct {
	ID    uuid.UUID
	Title sql.NullString
}

type SyUser struct {
	ID         uuid.UUID
	Email      sql.NullString
	Password   sql.NullString
	SaltRounds sql.NullInt32
	FirstName  sql.NullString
	LastName   sql.NullString
	Birthdate  sql.NullTime
}

type SyUserRole struct {
	UserID uuid.NullUUID
	RoleID uuid.NullUUID
}
