// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package movie_resevation

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addGenreToMovie = `-- name: AddGenreToMovie :exec
INSERT INTO mv_movie_genres 
(movie_id, genre_id)
VALUES
($1, (SELECT g.id FROM mv_genre g WHERE g.title = $2))
`

type AddGenreToMovieParams struct {
	MovieID uuid.NullUUID  `json:"movie_id"`
	Title   sql.NullString `json:"title"`
}

func (q *Queries) AddGenreToMovie(ctx context.Context, arg AddGenreToMovieParams) error {
	_, err := q.db.ExecContext(ctx, addGenreToMovie, arg.MovieID, arg.Title)
	return err
}

const createGenre = `-- name: CreateGenre :one
INSERT INTO mv_genre 
(title)
VALUES
($1)
RETURNING id, title
`

func (q *Queries) CreateGenre(ctx context.Context, title sql.NullString) (MvGenre, error) {
	row := q.db.QueryRowContext(ctx, createGenre, title)
	var i MvGenre
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO mv_movie
(title, description, poster_image, poster_ext, minutes, release_date, language, country_origin)
VALUES
($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, description, poster_image, poster_ext, minutes, release_date, language, country_origin
`

type CreateMovieParams struct {
	Title         sql.NullString `json:"title"`
	Description   sql.NullString `json:"description"`
	PosterImage   sql.NullString `json:"poster_image"`
	PosterExt     sql.NullString `json:"poster_ext"`
	Minutes       sql.NullInt32  `json:"minutes"`
	ReleaseDate   sql.NullTime   `json:"release_date"`
	Language      sql.NullString `json:"language"`
	CountryOrigin sql.NullString `json:"country_origin"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (MvMovie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Title,
		arg.Description,
		arg.PosterImage,
		arg.PosterExt,
		arg.Minutes,
		arg.ReleaseDate,
		arg.Language,
		arg.CountryOrigin,
	)
	var i MvMovie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PosterImage,
		&i.PosterExt,
		&i.Minutes,
		&i.ReleaseDate,
		&i.Language,
		&i.CountryOrigin,
	)
	return i, err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM mv_genre
WHERE id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGenre, id)
	return err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM mv_movie
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMovie, id)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT m.id, m.title, m.description, m.poster_image, m.poster_ext, m.minutes, m.release_date, m.language, m.country_origin, 
    COALESCE(
        (
            SELECT array_agg(g.title)
            FROM mv_genre g
            JOIN mv_movie_genres mg ON g.id = mg.genre_id
            WHERE mg.movie_id = m.id
        ), 
        '{}'::text[]
    )::text[] as genres
FROM mv_movie m
WHERE m.id = $1 LIMIT 1
`

type GetMovieRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         sql.NullString `json:"title"`
	Description   sql.NullString `json:"description"`
	PosterImage   sql.NullString `json:"poster_image"`
	PosterExt     sql.NullString `json:"poster_ext"`
	Minutes       sql.NullInt32  `json:"minutes"`
	ReleaseDate   sql.NullTime   `json:"release_date"`
	Language      sql.NullString `json:"language"`
	CountryOrigin sql.NullString `json:"country_origin"`
	Genres        []string       `json:"genres"`
}

func (q *Queries) GetMovie(ctx context.Context, id uuid.UUID) (GetMovieRow, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i GetMovieRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PosterImage,
		&i.PosterExt,
		&i.Minutes,
		&i.ReleaseDate,
		&i.Language,
		&i.CountryOrigin,
		pq.Array(&i.Genres),
	)
	return i, err
}

const getMovies = `-- name: GetMovies :many
SELECT m.id, m.title, m.description, m.poster_image, m.poster_ext, m.minutes, m.release_date, m.language, m.country_origin, 
    COALESCE(
        (
            SELECT array_agg(g.title)
            FROM mv_genre g
            JOIN mv_movie_genres mg ON g.id = mg.genre_id
            WHERE mg.movie_id = m.id
        ), 
        '{}'::text[]
    )::text[] as genres
FROM mv_movie m
ORDER BY title
`

type GetMoviesRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         sql.NullString `json:"title"`
	Description   sql.NullString `json:"description"`
	PosterImage   sql.NullString `json:"poster_image"`
	PosterExt     sql.NullString `json:"poster_ext"`
	Minutes       sql.NullInt32  `json:"minutes"`
	ReleaseDate   sql.NullTime   `json:"release_date"`
	Language      sql.NullString `json:"language"`
	CountryOrigin sql.NullString `json:"country_origin"`
	Genres        []string       `json:"genres"`
}

func (q *Queries) GetMovies(ctx context.Context) ([]GetMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviesRow
	for rows.Next() {
		var i GetMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.PosterImage,
			&i.PosterExt,
			&i.Minutes,
			&i.ReleaseDate,
			&i.Language,
			&i.CountryOrigin,
			pq.Array(&i.Genres),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGenreFromMovie = `-- name: RemoveGenreFromMovie :exec
DELETE FROM mv_movie_genres
WHERE movie_id = $1 AND genre_id = (SELECT g.id FROM mv_genre g WHERE g.title = $2)
`

type RemoveGenreFromMovieParams struct {
	MovieID uuid.NullUUID  `json:"movie_id"`
	Title   sql.NullString `json:"title"`
}

func (q *Queries) RemoveGenreFromMovie(ctx context.Context, arg RemoveGenreFromMovieParams) error {
	_, err := q.db.ExecContext(ctx, removeGenreFromMovie, arg.MovieID, arg.Title)
	return err
}

const updateMovie = `-- name: UpdateMovie :exec
UPDATE mv_movie
SET 
    title          = COALESCE($1, title),
    description    = COALESCE($2, description),
    poster_image   = COALESCE($3, poster_image),
    poster_ext     = COALESCE($4, poster_ext),
    minutes        = COALESCE($5, minutes),
    release_date   = COALESCE($6, release_date),
    language       = COALESCE($7, language),
    country_origin = COALESCE($8, country_origin)
WHERE
    id = $9
`

type UpdateMovieParams struct {
	Title         sql.NullString `json:"title"`
	Description   sql.NullString `json:"description"`
	PosterImage   sql.NullString `json:"poster_image"`
	PosterExt     sql.NullString `json:"poster_ext"`
	Minutes       sql.NullInt32  `json:"minutes"`
	ReleaseDate   sql.NullTime   `json:"release_date"`
	Language      sql.NullString `json:"language"`
	CountryOrigin sql.NullString `json:"country_origin"`
	ID            uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) error {
	_, err := q.db.ExecContext(ctx, updateMovie,
		arg.Title,
		arg.Description,
		arg.PosterImage,
		arg.PosterExt,
		arg.Minutes,
		arg.ReleaseDate,
		arg.Language,
		arg.CountryOrigin,
		arg.ID,
	)
	return err
}
