// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package movie_resevation

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO mv_people
(id, first_name, last_name, gender)
VALUES
($1, $2, $3, $4)
RETURNING id, first_name, last_name, gender
`

type CreatePersonParams struct {
	ID        uuid.UUID
	FirstName sql.NullString
	LastName  sql.NullString
	Gender    NullGenderEnum
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (MvPerson, error) {
	row := q.db.QueryRowContext(ctx, createPerson,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
	)
	var i MvPerson
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
	)
	return i, err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM mv_people
WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePerson, id)
	return err
}

const getPeople = `-- name: GetPeople :many
SELECT id, first_name, last_name, gender FROM mv_people
ORDER BY first_name
`

func (q *Queries) GetPeople(ctx context.Context) ([]MvPerson, error) {
	rows, err := q.db.QueryContext(ctx, getPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MvPerson
	for rows.Next() {
		var i MvPerson
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerson = `-- name: GetPerson :one
SELECT id, first_name, last_name, gender FROM mv_people
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (MvPerson, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i MvPerson
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
	)
	return i, err
}

const totalMalePeople = `-- name: TotalMalePeople :one
SELECT COUNT(*) FROM mv_people
WHERE gender = 'M'
`

func (q *Queries) TotalMalePeople(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, totalMalePeople)
	var count int64
	err := row.Scan(&count)
	return count, err
}
