// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package movie_resevation

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddGenreToMovie(ctx context.Context, arg AddGenreToMovieParams) error
	CreateGenre(ctx context.Context, title sql.NullString) (MvGenre, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (MvMovie, error)
	DeleteGenre(ctx context.Context, id uuid.UUID) error
	DeleteMovie(ctx context.Context, id uuid.UUID) error
	GetMovie(ctx context.Context, id uuid.UUID) (GetMovieRow, error)
	GetMovies(ctx context.Context) ([]GetMoviesRow, error)
	RemoveGenreFromMovie(ctx context.Context, arg RemoveGenreFromMovieParams) error
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) error
}

var _ Querier = (*Queries)(nil)
