// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package movie_resevation

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO mv_movie
(title, description, poster_image, poster_ext, release_date, language, country_origin)
VALUES
($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, poster_image, poster_ext, minutes, release_date, language, country_origin
`

type CreateMovieParams struct {
	Title         sql.NullString
	Description   sql.NullString
	PosterImage   sql.NullString
	PosterExt     sql.NullString
	ReleaseDate   sql.NullTime
	Language      sql.NullString
	CountryOrigin sql.NullString
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (MvMovie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Title,
		arg.Description,
		arg.PosterImage,
		arg.PosterExt,
		arg.ReleaseDate,
		arg.Language,
		arg.CountryOrigin,
	)
	var i MvMovie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PosterImage,
		&i.PosterExt,
		&i.Minutes,
		&i.ReleaseDate,
		&i.Language,
		&i.CountryOrigin,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM mv_movie
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMovie, id)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, description, poster_image, poster_ext, minutes, release_date, language, country_origin FROM mv_movie
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMovie(ctx context.Context, id uuid.UUID) (MvMovie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i MvMovie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PosterImage,
		&i.PosterExt,
		&i.Minutes,
		&i.ReleaseDate,
		&i.Language,
		&i.CountryOrigin,
	)
	return i, err
}

const getMovies = `-- name: GetMovies :many
SELECT id, title, description, poster_image, poster_ext, minutes, release_date, language, country_origin FROM mv_movie
ORDER BY title
`

func (q *Queries) GetMovies(ctx context.Context) ([]MvMovie, error) {
	rows, err := q.db.QueryContext(ctx, getMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MvMovie
	for rows.Next() {
		var i MvMovie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.PosterImage,
			&i.PosterExt,
			&i.Minutes,
			&i.ReleaseDate,
			&i.Language,
			&i.CountryOrigin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :exec
UPDATE mv_movie
SET 
    title = CASE WHEN $1::boolean
        THEN $2::VARCHAR(50) ELSE title END
WHERE
    id = $3
RETURNING id, title, description, poster_image, poster_ext, minutes, release_date, language, country_origin
`

type UpdateMovieParams struct {
	TitleDoUpdate bool
	Title         string
	ID            uuid.UUID
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) error {
	_, err := q.db.ExecContext(ctx, updateMovie, arg.TitleDoUpdate, arg.Title, arg.ID)
	return err
}
