// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	SaltRounds int32     `json:"salt_rounds"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	Birthdate  time.Time `json:"birthdate"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
