// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package auth

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, email, password, salt_rounds, first_name, last_name, birthdate, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.SaltRounds,
		&i.FirstName,
		&i.LastName,
		&i.Birthdate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
